Repository Wanted-Pre-Onboarding-FE-Team-12/pre-onboarding-assignment-week-4-1-team-12, pull requests merged in 2022-09, with the labels that each got.

#9 Feature/account list
  src/api/accountApi.js
  src/api/userApi.js
  src/components/Header/index.jsx
  src/pages/AccountList/AccountSubTitle/AccountSubTitle.jsx
  src/pages/AccountList/ListItem/index.jsx
  src/pages/AccountList/index.jsx
  src/store/modules/accountSlice.js
  src/store/modules/index.js
  src/utils/account.js
  src/utils/menuItem.js
Labels: PR, layout, feature, setting

#10 Feature/account detail
  src/api/accountApi.js
  src/pages/AccountDetail/index.jsx
  src/pages/AccountList/AccountSubTitle/index.jsx
  src/pages/AccountList/ListItem/index.jsx
  src/pages/AccountList/index.jsx
  src/utils/account.js
Labels: feature

#11 feature: filtering
  package-lock.json
  package.json
  src/api/accountApi.js
  src/pages/AccountList/AccountActiveSelectOption/index.jsx
  src/pages/AccountList/AccountBankSelectOption/index.jsx
  src/pages/AccountList/AccountSearch/index.jsx
  src/pages/AccountList/AccountStatusSelectOption/index.jsx
  src/pages/AccountList/AccountSubTitle/index.jsx
  src/pages/AccountList/ListItem/index.jsx
  src/pages/AccountList/index.jsx
Labels: layout, feature

#12 Feature/sidebar
  src/App.js
  src/components/MenuItem/index.jsx
  src/components/MenuItem/style.js
  src/components/Sidebar/index.jsx
  src/components/Sidebar/style.js
  src/hooks/useToastMessage.js
  src/layout/index.jsx
  src/store/modules/authSlice.js
  src/store/modules/commonSlice.js
  src/styles/globalStyle.js
  src/styles/theme.js
Labels: PR, layout, feature

#18 Feature/pagenation
  src/api/accountApi.js
  src/components/PageButton/Button/index.jsx
  src/components/PageButton/index.jsx
  src/pages/AccountDetail/index.jsx
  src/pages/AccountList/AccountActiveSelectOption/index.jsx
  src/pages/AccountList/AccountSearch/index.jsx
  src/pages/AccountList/AccountStatusSelectOption/index.jsx
  src/pages/AccountList/AccountSubTitle/index.jsx
  src/pages/AccountList/ListItem/index.jsx
  src/pages/AccountList/index.jsx
  src/store/modules/accountSlice.js
  src/utils/toastMessage.js
Labels: feature

#20 feature: account page
  package-lock.json
  package.json
  src/api/accountApi.js
  src/api/userApi.js
  src/components/Header/index.jsx
  src/components/Loading/index.jsx
  src/components/PageButton/Button/index.jsx
  src/components/PageButton/index.jsx
  src/pages/AccountDetail/index.jsx
  src/pages/AccountList/AccountActiveSelectOption/index.jsx
  src/pages/AccountList/AccountBankSelectOption/index.jsx
  src/pages/AccountList/AccountSearch/index.jsx
  src/pages/AccountList/AccountStatusSelectOption/index.jsx
  src/pages/AccountList/AccountSubTitle/index.jsx
  src/pages/AccountList/ListItem/index.jsx
  src/pages/AccountList/index.jsx
  src/store/modules/accountSlice.js
  src/store/modules/index.js
  src/utils/account.js
  src/utils/menuItem.js
  src/utils/toastMessage.js
Labels: PR, layout, feature
